//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string dob { get; set; }
        public string email { get; set; }
        public string C_from { get; set; }
        public string full_name { get; set; }
        public Nullable<bool> gender { get; set; }
        public string last_login { get; set; }
        public string mobile { get; set; }
        public string picture { get; set; }
        public Nullable<bool> stt { get; set; }
        public Nullable<bool> file_datas { get; set; }
    }
}
