//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Courseworks = new HashSet<Coursework>();
            this.Courseworks1 = new HashSet<Coursework>();
            this.Grades = new HashSet<Grade>();
            this.Registrations = new HashSet<Registration>();
        }
    
        public int course_id { get; set; }
        public int subject_id { get; set; }
        public int teacher_id { get; set; }
        public bool course_is_default { get; set; }
        public string course_start_date { get; set; }
        public string course_end_date { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Coursework> Courseworks { get; set; }
        public virtual ICollection<Coursework> Courseworks1 { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
