//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int course_id { get; set; }
        public int subject_id { get; set; }
        public int teacher_id { get; set; }
        public bool course_is_default { get; set; }
        public string course_start_date { get; set; }
        public string course_end_date { get; set; }
    }
}
