//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.ExamConfigs = new HashSet<ExamConfig>();
            this.TestResults = new HashSet<TestResult>();
        }
    
        public int exam_id { get; set; }
        public string exam_level { get; set; }
        public string exam_name { get; set; }
        public bool exam_is_practice { get; set; }
    
        public virtual ICollection<ExamConfig> ExamConfigs { get; set; }
        public virtual ICollection<TestResult> TestResults { get; set; }
    }
}
