//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPWy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamConfig
    {
        public int exam_config_id { get; set; }
        public int exam_id { get; set; }
        public int domain_id { get; set; }
        public string domain_size { get; set; }
        public int lesson_id { get; set; }
        public string lesson_size { get; set; }
        public string keywords { get; set; }
    
        public virtual Exam Exam { get; set; }
    }
}
