//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.RolePermissions = new HashSet<RolePermission>();
        }
    
        public int permission_id { get; set; }
        public string permission_name { get; set; }
        public string permission_link { get; set; }
        public Nullable<bool> permission_status { get; set; }
    
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}
