//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int question_id { get; set; }
        public int subject_id { get; set; }
        public int domain_id { get; set; }
        public int lesson_id { get; set; }
        public string level { get; set; }
    }
}
