//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public Registration()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public int registration_id { get; set; }
        public int user_id { get; set; }
        public int course_id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual User User { get; set; }
    }
}
