//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMenu
    {
        public int role_menu_id { get; set; }
        public int role_id { get; set; }
        public int menu_id { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
