//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roll
    {
        public roll()
        {
            this.user_roll = new HashSet<user_roll>();
        }
    
        public int roll_id { get; set; }
        public string roll_name { get; set; }
    
        public virtual ICollection<user_roll> user_roll { get; set; }
    }
}
