//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int subject_id { get; set; }
        public string subject_category { get; set; }
        public string subject_tag_line { get; set; }
        public string subject_brief_info { get; set; }
    }
}
