//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestBatch
    {
        public TestBatch()
        {
            this.TestResults = new HashSet<TestResult>();
        }
    
        public int batch_id { get; set; }
        public string batch_name { get; set; }
    
        public virtual ICollection<TestResult> TestResults { get; set; }
    }
}
